#!/usr/bin/env python3
"""Verify a Back Channel crypto-v1 vectors file with an independent stack.

    python interop/verify_vectors.py [path/to/crypto-v1.json]

Default path: vectors/crypto-v1.json. Exits 0 if every vector passes, 1 otherwise.

WHY THIS EXISTS. The vitest suite checks the two in-repo JavaScript
implementations against vectors generated by node:crypto. Node's ECDH point
multiply is OpenSSL in both the generator and the library, so that check pins
the *composition* (encodings, HKDF parameters, envelope shape) rather than the
primitives themselves. This script runs the same vectors through the `cryptography`
package's own stack — the primitives the skill's Python recipe uses — which is
where genuine primitive-level independence comes from.

Requires: pip install cryptography

Deliberately NOT wired into `npm test` or CI: CI images aren't guaranteed to
have Python plus `cryptography`. Run it by hand when the vectors change.
"""

import json
import sys
from pathlib import Path

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from base64 import b64decode

HKDF_INFO = b"back-channel/v1/session-key"
HKDF_SALT = b"\x00" * 32
KEY_LEN = 32


def derive_session_key(shared_secret: bytes) -> bytes:
    """HKDF-SHA-256, zero salt, the v1 info string, 32-byte output."""
    return HKDF(
        algorithm=hashes.SHA256(),
        length=KEY_LEN,
        salt=HKDF_SALT,
        info=HKDF_INFO,
    ).derive(shared_secret)


class Results:
    def __init__(self) -> None:
        self.failures: list[str] = []

    def check(self, ok: bool, label: str) -> None:
        if not ok:
            self.failures.append(label)

    def section(self, name: str, count: int, before: int) -> None:
        failed = len(self.failures) - before
        status = "PASS" if failed == 0 else f"FAIL ({failed})"
        print(f"  {name:<18} {count:>3} vectors  {status}")


def verify_hkdf(vectors, r: Results) -> None:
    before = len(r.failures)
    for v in vectors:
        got = derive_session_key(bytes.fromhex(v["ikm_hex"]))
        r.check(got.hex() == v["session_key_hex"], f"hkdf/{v['name']}")
    r.section("hkdf", len(vectors), before)


def verify_ecdh(vectors, r: Results) -> None:
    before = len(r.failures)
    for v in vectors:
        name = v["name"]
        alice = ec.derive_private_key(
            int(v["alice_private_hex"], 16), ec.SECP256R1()
        )
        bob = ec.derive_private_key(int(v["bob_private_hex"], 16), ec.SECP256R1())

        # Public keys are the uncompressed point, base64 on the wire.
        alice_pub = alice.public_key().public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.UncompressedPoint,
        )
        r.check(
            alice_pub == b64decode(v["alice_public_b64"]),
            f"ecdh/{name}/alice_public",
        )

        peer_bob = ec.EllipticCurvePublicKey.from_encoded_point(
            ec.SECP256R1(), b64decode(v["bob_public_b64"])
        )
        peer_alice = ec.EllipticCurvePublicKey.from_encoded_point(
            ec.SECP256R1(), b64decode(v["alice_public_b64"])
        )

        secret_a = alice.exchange(ec.ECDH(), peer_bob)
        secret_b = bob.exchange(ec.ECDH(), peer_alice)
        r.check(secret_a == secret_b, f"ecdh/{name}/sides_agree")
        r.check(
            secret_a.hex() == v["shared_secret_hex"], f"ecdh/{name}/shared_secret"
        )
        r.check(
            derive_session_key(secret_a).hex() == v["session_key_hex"],
            f"ecdh/{name}/session_key",
        )
    r.section("ecdh_p256", len(vectors), before)


def verify_envelope(vectors, r: Results) -> None:
    """Both directions. Layer 1 is byte-exact; Layer 2 is semantic."""
    before = len(r.failures)
    for v in vectors:
        name = v["name"]
        key = bytes.fromhex(v["key_hex"])
        iv = b64decode(v["iv_b64"])
        expected_ct = b64decode(v["envelope"]["ct"])
        expected_tag = b64decode(v["envelope"]["tag"])

        # Layer 1, ENCRYPT: encrypt the exact recorded plaintext bytes. Never
        # re-serialize v["plaintext"] — Python's json.dumps inserts spaces and
        # would produce different bytes, hence a different ciphertext.
        plaintext_bytes = v["plaintext_json"].encode("utf-8")
        sealed = AESGCM(key).encrypt(iv, plaintext_bytes, None)
        # AESGCM returns ct || tag concatenated.
        r.check(sealed == expected_ct + expected_tag, f"envelope/{name}/encrypt")

        # Layer 1, DECRYPT: recover exactly those bytes.
        opened = AESGCM(key).decrypt(iv, expected_ct + expected_tag, None)
        r.check(opened == plaintext_bytes, f"envelope/{name}/decrypt_bytes")

        # Layer 2: parse and compare semantically.
        r.check(
            json.loads(opened.decode("utf-8")) == v["plaintext"],
            f"envelope/{name}/decrypt_semantic",
        )
    r.section("envelope", len(vectors), before)


def verify_envelope_reject(vectors, r: Results) -> None:
    """Every one of these MUST be refused."""
    before = len(r.failures)
    for v in vectors:
        name = v["name"]
        key = bytes.fromhex(v["key_hex"])
        env = v["envelope"]
        refused = False
        try:
            if env.get("v") != 1:
                refused = True  # version check, before any crypto
            else:
                iv = b64decode(env["iv"])
                if len(iv) != 12:
                    refused = True  # length check, before any crypto
                else:
                    AESGCM(key).decrypt(
                        iv, b64decode(env["ct"]) + b64decode(env["tag"]), None
                    )
        except (InvalidTag, ValueError):
            refused = True
        r.check(refused, f"envelope_reject/{name} (expected refusal)")
    r.section("envelope_reject", len(vectors), before)


def main() -> int:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "vectors/crypto-v1.json")
    if not path.is_file():
        print(f"vectors file not found: {path}", file=sys.stderr)
        return 1

    data = json.loads(path.read_text(encoding="utf-8"))
    meta = data.get("_meta", {})
    print(f"{meta.get('name', path.name)} (version {meta.get('version')})")
    print(f"source: {path}\n")

    r = Results()
    verify_hkdf(data["hkdf"], r)
    verify_ecdh(data["ecdh_p256"], r)
    verify_envelope(data["envelope"], r)
    verify_envelope_reject(data["envelope_reject"], r)

    if r.failures:
        print(f"\nFAILED ({len(r.failures)}):")
        for f in r.failures:
            print(f"  - {f}")
        return 1
    print("\nAll vectors pass — this implementation is crypto-v1 conforming.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
